// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uwp.SQLite.Model;

namespace Uwp.SQLite.Model.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25");

            modelBuilder.Entity("Uwp.SQLite.Model.FolderModel", b =>
                {
                    b.Property<int>("FolderModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Create_On")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("FolderModelId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("Uwp.SQLite.Model.StudyModel", b =>
                {
                    b.Property<int>("StudyModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Create_On")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("FolderModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudyModelId");

                    b.HasIndex("FolderModelId");

                    b.ToTable("Studies");
                });

            modelBuilder.Entity("Uwp.SQLite.Model.TopicModel", b =>
                {
                    b.Property<int>("TopicModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Defination")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudyModelId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("hasItem")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isFavorite")
                        .HasColumnType("INTEGER");

                    b.HasKey("TopicModelId");

                    b.HasIndex("StudyModelId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("Uwp.SQLite.Model.StudyModel", b =>
                {
                    b.HasOne("Uwp.SQLite.Model.FolderModel", "FolderModel")
                        .WithMany("StudyModels")
                        .HasForeignKey("FolderModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Uwp.SQLite.Model.TopicModel", b =>
                {
                    b.HasOne("Uwp.SQLite.Model.StudyModel", "StudyModel")
                        .WithMany("TopicModels")
                        .HasForeignKey("StudyModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
